#!/usr/bin/env bash

DOTFILES_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source "$DOTFILES_DIR/system/.function"

if confirm "Back up existing dotfiles? (y/n)"; then
  BACKUPS="$HOME/backup_dotfiles_$(date +"%Y_%m_%d_%H%M%S")"
  mkdir "$BACKUPS"

  FILES="
    agignore
    bash_profile
    ctagsignore
    eslintrc.json
    git-completion.bash
    gitconfig
    gitignore_global
    iex.exs
    inputrc
    jshintrc
    railsrc
    rspec
    ruby-version
    tmux.conf
    vimrc
  "

  for DOTFILE in $FILES; do
    [ -f "$HOME/.$DOTFILE" ] && mv "$HOME/.$DOTFILE" "$BACKUPS"
  done

  [ -d ~/bin ] && mv ~/bin "$BACKUPS"
  [ -d ~/system ] && mv ~/system "$BACKUPS"
  [ -d ~/.vim ] && mv ~/.vim "$BACKUPS"
fi

if confirm "Link new dotfiles? (y/n)"; then
  for DOTFILE in $DOTFILES_DIR/{vim,git,ruby,elixir,js,runcom}/.*; do
    [ -f "$DOTFILE" ] && ln -sf "$DOTFILE" ~
  done

  ln -sf "$DOTFILES_DIR/git/.git_template" ~
  ln -sf "$DOTFILES_DIR/system/" ~
  ln -sf "$DOTFILES_DIR/bin/" ~
  mkdir ~/.vim
  ln -sf "$DOTFILES_DIR/vim/templates" ~/.vim
fi

git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

